version: "3.7"

services:
  mysequel:
    container_name: lab-3-mysequel
    image: mysql:latest
    # volumes:
    #   - type: bind
    #     source: .
    #     target: /docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=cdf
    ports:
      - "3306:3306"
    stdin_open: true
    tty: true
    command: --default-authentication-plugin=mysql_native_password > /docker-entrypoint-initdb.d/output_logs.txt